services:
  whishify:
    image: ghcr.io/fufn/wishify:latest
    ports:
      - "127.0.0.1:8317:8317"
    volumes:
      - ./logs:/wishify/logs
    environment:
      - DB_HOST=172.18.0.1
      - DB_USERNAME=postgres
      - DB_PASSWORD=1234
      - DB_NAME=wishify
    restart: no