services:
  whishify:
    image: ghcr.io/fufn/wishify:latest
    ports:
      - "8317:8317"
    environment:
      - DB_HOST=host.docker.internal
      - DB_USERNAME=postgres
      - DB_PASSWORD=1234
      - DB_NAME=wishify
    restart: unless-stopped